# Generated by Django 3.0.4 on 2020-07-21 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empyloeeapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9)),
                ('category_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='location',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=9),
        ),
        migrations.CreateModel(
            name='child_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_product_name', models.CharField(max_length=20)),
                ('child_product_no', models.ManyToManyField(to='empyloeeapi.category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='category_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empyloeeapi.product'),
        ),
    ]
